<template>
 <div class="search-s1">
   <ul>
     <li>全部包类</li>
     <li>双肩包</li>
     <li>手领包/单肩包</li>
     <li>钱包/卡包/手包/钥匙包</li>
     <li>腰包</li>
     <li>邮差包</li>
     <li>电脑包</li>
     <li>储物包</li>
     <li>环保包</li>
     <li>包配</li>
     <li>tote包</li>
     <li>旅行包</li>
     <li>mini包</li>
     <li>剑桥包</li>
   </ul>
 </div>
</template>
