<template>
 <div class="search-s1">
   <ul>
     <li>全部上衣</li>
     <li>棉衣</li>
     <li>羽绒服</li>
     <li>大衣/风衣</li>
     <li>夹克</li>
     <li>卫衣</li>
     <li>毛衣/针织</li>
     <li>防风外套</li>
     <li>皮衣</li>
     <li>衬衫</li>
     <li>西装</li>
     <li>T恤</li>
     <li>POLO</li>
     <li>背心</li>
     <li>套装</li>
     <li>马甲</li>
   </ul>
 </div>
</template>
